name: tiny-crf
type: ddit
hidden_size: 512
cond_dim: 128
length: 256
n_blocks: 6
n_heads: 8
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: False

crf:
  decoder_layers: 2
  decoder_heads: 8
  decoder_dim: 256
  top_k: 32
